export enum Screens {
    MAIN_TAB = 'MAIN_TAB',
    HOME = 'HOME',
    SETTINGS = 'SETTINGS',
    EXPENSE_OPERATIONS = 'EXPENSE_OPERATIONS',
    EXPENSE_ADD_MANUAL = 'EXPENSE_ADD_MANUAL',
    EXPENSE_SCAN_QR = 'EXPENSE_SCAN_QR',
    

}
